# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GithubNippou < Formula
  desc "Print today's your GitHub activity for issues and pull requests"
  homepage "https://github.com/masutaka/github-nippou"
  version "4.2.40"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/masutaka/github-nippou/releases/download/v4.2.40/github-nippou_v4.2.40_darwin_amd64.zip"
      sha256 "6c5c759a35ea2d8b77bfbd35502b605f17abc80c939a9c41b6b7e3cb2881588e"

      def install
        bin.install 'github-nippou'

        # Install bash completion
        output = Utils.safe_popen_read("#{bin}/github-nippou", 'completion', 'bash')
        (bash_completion/'github-nippou').write output

        # Install fish completion
        output = Utils.safe_popen_read("#{bin}/github-nippou", 'completion', 'fish')
        (fish_completion/'github-nippou.fish').write output

        # Install zsh completion
        output = Utils.safe_popen_read("#{bin}/github-nippou", 'completion', 'zsh')
        (zsh_completion/'_github-nippou').write output
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/masutaka/github-nippou/releases/download/v4.2.40/github-nippou_v4.2.40_darwin_arm64.zip"
      sha256 "d96b4714863080d6800aebbd0e09c6dc93dd5cb7668693dba3f79013c9e4eb38"

      def install
        bin.install 'github-nippou'

        # Install bash completion
        output = Utils.safe_popen_read("#{bin}/github-nippou", 'completion', 'bash')
        (bash_completion/'github-nippou').write output

        # Install fish completion
        output = Utils.safe_popen_read("#{bin}/github-nippou", 'completion', 'fish')
        (fish_completion/'github-nippou.fish').write output

        # Install zsh completion
        output = Utils.safe_popen_read("#{bin}/github-nippou", 'completion', 'zsh')
        (zsh_completion/'_github-nippou').write output
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/masutaka/github-nippou/releases/download/v4.2.40/github-nippou_v4.2.40_linux_amd64.zip"
      sha256 "676854802d21fac7a24d4e9e8b3a92fed7940a0970715f817ed100f31888de2e"
      def install
        bin.install 'github-nippou'

        # Install bash completion
        output = Utils.safe_popen_read("#{bin}/github-nippou", 'completion', 'bash')
        (bash_completion/'github-nippou').write output

        # Install fish completion
        output = Utils.safe_popen_read("#{bin}/github-nippou", 'completion', 'fish')
        (fish_completion/'github-nippou.fish').write output

        # Install zsh completion
        output = Utils.safe_popen_read("#{bin}/github-nippou", 'completion', 'zsh')
        (zsh_completion/'_github-nippou').write output
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/masutaka/github-nippou/releases/download/v4.2.40/github-nippou_v4.2.40_linux_arm64.zip"
      sha256 "70c262025fd2069c06cb7ca5a1ac47dfd9e4bcd33d9449f9989a19eaa535202c"
      def install
        bin.install 'github-nippou'

        # Install bash completion
        output = Utils.safe_popen_read("#{bin}/github-nippou", 'completion', 'bash')
        (bash_completion/'github-nippou').write output

        # Install fish completion
        output = Utils.safe_popen_read("#{bin}/github-nippou", 'completion', 'fish')
        (fish_completion/'github-nippou.fish').write output

        # Install zsh completion
        output = Utils.safe_popen_read("#{bin}/github-nippou", 'completion', 'zsh')
        (zsh_completion/'_github-nippou').write output
      end
    end
  end

  test do
    system 'github-nippou', 'version'
  end
end
