# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GithubNippou < Formula
  desc "Print today's your GitHub activity for issues and pull requests"
  homepage "https://github.com/masutaka/github-nippou"
  version "4.2.45"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/masutaka/github-nippou/releases/download/v4.2.45/github-nippou_v4.2.45_darwin_amd64.zip"
      sha256 "aa3a21be74d5c7ee60b7af220f4ee71b49512b9ff76927d36dc9bea23937feb2"

      def install
        bin.install 'github-nippou'

        # Install bash completion
        output = Utils.safe_popen_read("#{bin}/github-nippou", 'completion', 'bash')
        (bash_completion/'github-nippou').write output

        # Install fish completion
        output = Utils.safe_popen_read("#{bin}/github-nippou", 'completion', 'fish')
        (fish_completion/'github-nippou.fish').write output

        # Install zsh completion
        output = Utils.safe_popen_read("#{bin}/github-nippou", 'completion', 'zsh')
        (zsh_completion/'_github-nippou').write output
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/masutaka/github-nippou/releases/download/v4.2.45/github-nippou_v4.2.45_darwin_arm64.zip"
      sha256 "53a59021aec0ac33145a8a901007efcb0cbf8acaea9c75c024e3b0a9b7639cb5"

      def install
        bin.install 'github-nippou'

        # Install bash completion
        output = Utils.safe_popen_read("#{bin}/github-nippou", 'completion', 'bash')
        (bash_completion/'github-nippou').write output

        # Install fish completion
        output = Utils.safe_popen_read("#{bin}/github-nippou", 'completion', 'fish')
        (fish_completion/'github-nippou.fish').write output

        # Install zsh completion
        output = Utils.safe_popen_read("#{bin}/github-nippou", 'completion', 'zsh')
        (zsh_completion/'_github-nippou').write output
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/masutaka/github-nippou/releases/download/v4.2.45/github-nippou_v4.2.45_linux_amd64.zip"
      sha256 "b17e500ef09495767998819e9784ff5195d1fb8316bf2aaf3009c63007fce798"
      def install
        bin.install 'github-nippou'

        # Install bash completion
        output = Utils.safe_popen_read("#{bin}/github-nippou", 'completion', 'bash')
        (bash_completion/'github-nippou').write output

        # Install fish completion
        output = Utils.safe_popen_read("#{bin}/github-nippou", 'completion', 'fish')
        (fish_completion/'github-nippou.fish').write output

        # Install zsh completion
        output = Utils.safe_popen_read("#{bin}/github-nippou", 'completion', 'zsh')
        (zsh_completion/'_github-nippou').write output
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/masutaka/github-nippou/releases/download/v4.2.45/github-nippou_v4.2.45_linux_arm64.zip"
      sha256 "4c969b6a5841c4d33d3a99479523e999a8ffc904c091d20283aa11cd6f0899dc"
      def install
        bin.install 'github-nippou'

        # Install bash completion
        output = Utils.safe_popen_read("#{bin}/github-nippou", 'completion', 'bash')
        (bash_completion/'github-nippou').write output

        # Install fish completion
        output = Utils.safe_popen_read("#{bin}/github-nippou", 'completion', 'fish')
        (fish_completion/'github-nippou.fish').write output

        # Install zsh completion
        output = Utils.safe_popen_read("#{bin}/github-nippou", 'completion', 'zsh')
        (zsh_completion/'_github-nippou').write output
      end
    end
  end

  test do
    system 'github-nippou', 'version'
  end
end
