# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GithubNippou < Formula
  desc "Print today's your GitHub activity for issues and pull requests"
  homepage "https://github.com/masutaka/github-nippou"
  version "4.2.44"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/masutaka/github-nippou/releases/download/v4.2.44/github-nippou_v4.2.44_darwin_amd64.zip"
      sha256 "3e8a08c9240d129715e42352ac687b1a8c02d10789928fc64101068c39d62f76"

      def install
        bin.install 'github-nippou'

        # Install bash completion
        output = Utils.safe_popen_read("#{bin}/github-nippou", 'completion', 'bash')
        (bash_completion/'github-nippou').write output

        # Install fish completion
        output = Utils.safe_popen_read("#{bin}/github-nippou", 'completion', 'fish')
        (fish_completion/'github-nippou.fish').write output

        # Install zsh completion
        output = Utils.safe_popen_read("#{bin}/github-nippou", 'completion', 'zsh')
        (zsh_completion/'_github-nippou').write output
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/masutaka/github-nippou/releases/download/v4.2.44/github-nippou_v4.2.44_darwin_arm64.zip"
      sha256 "a947f6d46355130b4152715a40615e4c5da5880bafaade112a9cfd45e739885d"

      def install
        bin.install 'github-nippou'

        # Install bash completion
        output = Utils.safe_popen_read("#{bin}/github-nippou", 'completion', 'bash')
        (bash_completion/'github-nippou').write output

        # Install fish completion
        output = Utils.safe_popen_read("#{bin}/github-nippou", 'completion', 'fish')
        (fish_completion/'github-nippou.fish').write output

        # Install zsh completion
        output = Utils.safe_popen_read("#{bin}/github-nippou", 'completion', 'zsh')
        (zsh_completion/'_github-nippou').write output
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/masutaka/github-nippou/releases/download/v4.2.44/github-nippou_v4.2.44_linux_amd64.zip"
      sha256 "9be66786e5d7f68bd7eed5e84a832f82ae4f9dfd305b42c77ef4298de95d4988"
      def install
        bin.install 'github-nippou'

        # Install bash completion
        output = Utils.safe_popen_read("#{bin}/github-nippou", 'completion', 'bash')
        (bash_completion/'github-nippou').write output

        # Install fish completion
        output = Utils.safe_popen_read("#{bin}/github-nippou", 'completion', 'fish')
        (fish_completion/'github-nippou.fish').write output

        # Install zsh completion
        output = Utils.safe_popen_read("#{bin}/github-nippou", 'completion', 'zsh')
        (zsh_completion/'_github-nippou').write output
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/masutaka/github-nippou/releases/download/v4.2.44/github-nippou_v4.2.44_linux_arm64.zip"
      sha256 "9c2219da77108e0e3abe05c1a91a6da225d1b4aafef5330a812612b47d17185f"
      def install
        bin.install 'github-nippou'

        # Install bash completion
        output = Utils.safe_popen_read("#{bin}/github-nippou", 'completion', 'bash')
        (bash_completion/'github-nippou').write output

        # Install fish completion
        output = Utils.safe_popen_read("#{bin}/github-nippou", 'completion', 'fish')
        (fish_completion/'github-nippou.fish').write output

        # Install zsh completion
        output = Utils.safe_popen_read("#{bin}/github-nippou", 'completion', 'zsh')
        (zsh_completion/'_github-nippou').write output
      end
    end
  end

  test do
    system 'github-nippou', 'version'
  end
end
