# This file was generated by GoReleaser. DO NOT EDIT.
cask "github-nippou" do
  version "4.3.3"

  on_macos do
    on_arm do
      sha256 "7d05a95bfe9b64f35ac860c9a08978c035d2553b41fa098dd75f5d543f137f9a"
      url "https://github.com/masutaka/github-nippou/releases/download/v#{version}/github-nippou_v#{version}_darwin_arm64.zip"
    end
    on_intel do
      sha256 "fd34bee48084893049074e16e622672bb728ac7ef648b8081f3c7d6fbb28e3aa"
      url "https://github.com/masutaka/github-nippou/releases/download/v#{version}/github-nippou_v#{version}_darwin_amd64.zip"
    end
  end
  on_linux do
    on_arm do
      sha256 "ad922e02084323b50e91434b69e6d2590122f4ef83821cc176a95e0afeb9e25c"
      url "https://github.com/masutaka/github-nippou/releases/download/v#{version}/github-nippou_v#{version}_linux_arm64.zip"
    end
    on_intel do
      sha256 "13e81fe6b96d4298f533cbf5d1db8b9b3d8f15126c17cc81d35bb2e7b661a659"
      url "https://github.com/masutaka/github-nippou/releases/download/v#{version}/github-nippou_v#{version}_linux_amd64.zip"
    end
  end

  name "github-nippou"
  desc "Print today's your GitHub activity for issues and pull requests"
  homepage "https://github.com/masutaka/github-nippou"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "github-nippou"

  preflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/github-nippou"]
    end
  end

  generate_completions_from_executable "github-nippou",
    shell_parameter_format: :cobra

  # No zap stanza required
end
