# This file was generated by GoReleaser. DO NOT EDIT.
cask "github-nippou" do
  version "4.3.2"

  on_macos do
    on_intel do
      sha256 "649664e66d1c190e17bc3fd2c88ed82e21ebc5df2f2ce1d355e912b1e711ab84"
      url "https://github.com/masutaka/github-nippou/releases/download/v#{version}/github-nippou_v#{version}_darwin_amd64.zip",
        verified: "github.com/masutaka/github-nippou/"
    end
    on_arm do
      sha256 "a7598c33787c7070f93505e4566939a551032a13be55b9f1bcba0cb6cba8a8d7"
      url "https://github.com/masutaka/github-nippou/releases/download/v#{version}/github-nippou_v#{version}_darwin_arm64.zip",
        verified: "github.com/masutaka/github-nippou/"
    end
  end

  on_linux do
    on_intel do
      sha256 "3efc144da0a3cbfefb36dae1e01c5ba3317c5f10c735dd0275930a6459df83b0"
      url "https://github.com/masutaka/github-nippou/releases/download/v#{version}/github-nippou_v#{version}_linux_amd64.zip",
        verified: "github.com/masutaka/github-nippou/"
    end
    on_arm do
      sha256 "c4bddf0a3c517fa1f5ffa424869de24fd900c6db401825d7fa1cdb0d3bd25873"
      url "https://github.com/masutaka/github-nippou/releases/download/v#{version}/github-nippou_v#{version}_linux_arm64.zip",
        verified: "github.com/masutaka/github-nippou/"
    end
  end

  name "github-nippou"
  desc "Print today's your GitHub activity for issues and pull requests"
  homepage "https://github.com/masutaka/github-nippou"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "github-nippou"

  preflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/github-nippou"]
    end
  end

  generate_completions_from_executable "github-nippou",
    shell_parameter_format: :cobra

  # No zap stanza required

end
