# This file was generated by GoReleaser. DO NOT EDIT.
cask "github-nippou" do
  version "4.3.1"

  on_macos do
    on_intel do
      sha256 "45208b80ac0c6c8889df1bb624896a5dd20fbb1b68063f2becc7a62d31e0eaa3"
      url "https://github.com/masutaka/github-nippou/releases/download/v#{version}/github-nippou_v#{version}_darwin_amd64.zip",
        verified: "github.com/masutaka/github-nippou/"
    end
    on_arm do
      sha256 "1e8964e32b99d6428c766539f4c47920e88438fba392d8f37f48e8271abd88d8"
      url "https://github.com/masutaka/github-nippou/releases/download/v#{version}/github-nippou_v#{version}_darwin_arm64.zip",
        verified: "github.com/masutaka/github-nippou/"
    end
  end

  on_linux do
    on_intel do
      sha256 "e23b874626b72d280c7eca8ebfc72ca1ee95fa9fcf9568720c15b9fbf4ba0e01"
      url "https://github.com/masutaka/github-nippou/releases/download/v#{version}/github-nippou_v#{version}_linux_amd64.zip",
        verified: "github.com/masutaka/github-nippou/"
    end
    on_arm do
      sha256 "99fde95ba08c471e5e229b95aa2de45df40f108c2ac99b8d38f37f3d80f2af6c"
      url "https://github.com/masutaka/github-nippou/releases/download/v#{version}/github-nippou_v#{version}_linux_arm64.zip",
        verified: "github.com/masutaka/github-nippou/"
    end
  end

  name "github-nippou"
  desc "Print today's your GitHub activity for issues and pull requests"
  homepage "https://github.com/masutaka/github-nippou"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "github-nippou"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/github-nippou"]
    end
  end
  generate_completions_from_executable "github-nippou", "completion",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  # No zap stanza required

end
